### ISSUE TITLE
Vite error when using TypeScript inside .svelte components

### ISSUE THREAD

**Issue by colgiati** [drannex42/svelte-capacitor#15]
Hello, I came across this template on reddit and decided to try it out. I use TypeScript for everything, so I also use it inside svelte components. Now, here's the issue I came across:

When I change the `<script>` tag in a .svelte file to `<script lang='ts'>` and then use a TypeScript syntax (for example type annotations), vite throws an error:

```
2:41:01 PM [vite] Internal server error: Unexpected token
  Plugin: vite-plugin-svelte
  File: /home/user/Documents/Projects/svelte-capacitor/src/pages/index.svelte
  1: <script lang="ts">
  2:     var name: string = 'svelte'
                 ^
  3:     var image = "assets/svelte_cap.png"
  4: </script>
      at error (/home/user/Documents/Projects/svelte-capacitor/node_modules/svelte/compiler.js:17701:20)
      at Parser$1.error (/home/user/Documents/Projects/svelte-capacitor/node_modules/svelte/compiler.js:17777:10)
      at Parser$1.acorn_error (/home/user/Documents/Projects/svelte-capacitor/node_modules/svelte/compiler.js:17771:15)
      at Object.read_script [as read] (/home/user/Documents/Projects/svelte-capacitor/node_modules/svelte/compiler.js:8469:17)
      at tag (/home/user/Documents/Projects/svelte-capacitor/node_modules/svelte/compiler.js:16860:34)
      at new Parser$1 (/home/user/Documents/Projects/svelte-capacitor/node_modules/svelte/compiler.js:17736:22)
      at parse$3 (/home/user/Documents/Projects/svelte-capacitor/node_modules/svelte/compiler.js:17868:21)
      at compile (/home/user/Documents/Projects/svelte-capacitor/node_modules/svelte/compiler.js:31282:18)
      at compileSvelte (/home/user/Documents/Projects/svelte-capacitor/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs:302:48)
      at async TransformContext.transform (/home/user/Documents/Projects/svelte-capacitor/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs:1150:27)
```
How to reproduce:
- Clone this repository
- Run `npm install`
- Change `<script>` tag to `<script lang='ts'>` in `index.svelte`
- Change `var name = 'svelte'` tag to `var name: string = 'svelte'` in `index.svelte`
- Run `npm run dev:start`
- Browse to http://localhost:5000/

Does anyone know how to fix this? Is this the expected behaviour or a bug? I'd be happy to provide a PR when I/we find a solution.
Thank you and have a nice day :)

**Comment by macleod-ee** [comment]
Go into your `vite.config.js` file and add `const preprocess = require('svelte-preprocess')` to the top of the file and change the plugins section to `plugins: [svelte({ preprocess: preprocess() })]`. 

It will look similar to this:

```
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { getAliases } from 'vite-aliases'

const preprocess = require('svelte-preprocess')
const aliases = getAliases();

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte({ preprocess: preprocess() })]
  publicDir: './assets/',
  build: {
    outDir: './public/'
  },
  resolve: {
    alias: aliases
  },
  optimizeDeps: { exclude: ["@roxi/routify", "@urql/svelte"] },
})
```

I believe older versions(?) of vite-plugin-svelte automatically called svelte.config.js and thats where the preprocess script was located. I don't know if it's still calling it, but I will be testing and making that the default if it works out. 

If this works for you, let me know and I will close this issue!

**Comment by colgiati** [comment]
Hello again, it seems to have solved the issue for me, thank you!
